-- MySQL Script generated by MySQL Workbench
-- 06/03/16 16:13:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fxuser
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fxuser
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fxuser` DEFAULT CHARACTER SET utf8 ;
USE `fxuser` ;

-- -----------------------------------------------------
-- Table `fxuser`.`fx_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fxuser`.`fx_user` (
  `uid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NOT NULL,
  `openid` VARCHAR(45) NULL,
  `headimgurl` VARCHAR(255) NULL,
  `money` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '账户余额',
  `up1` INT UNSIGNED NOT NULL COMMENT '一级上属id',
  `up2` INT UNSIGNED NOT NULL COMMENT '二级上属id',
  `leader` INT UNSIGNED NOT NULL COMMENT '团队领导人id',
  `agent` TINYINT(8) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否是代理，默认不是0',
  `vip` DECIMAL(10,2) UNSIGNED NOT NULL COMMENT '自己的级别',
  PRIMARY KEY (`uid`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `fxuser`.`fx_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fxuser`.`fx_order` (
  `oid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT(10) UNSIGNED NOT NULL,
  `gid` INT(10) UNSIGNED NOT NULL,
  `time` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `addr` VARCHAR(45) NULL,
  `city` INT UNSIGNED NOT NULL COMMENT '城市代码',
  `money` DECIMAL(10,2) UNSIGNED NOT NULL COMMENT '购买价',
  `status` TINYINT(8) UNSIGNED NOT NULL COMMENT '支付状态',
  PRIMARY KEY (`oid`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `fxuser`.`fx_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fxuser`.`fx_goods` (
  `gid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL COMMENT '价格',
  `self` DECIMAL(10,2) NULL COMMENT '自己红包',
  `up1` DECIMAL(10,2) UNSIGNED NOT NULL COMMENT '一级红包',
  `up2` DECIMAL(10,2) UNSIGNED NOT NULL COMMENT '二级红包',
  `leader` DECIMAL(10,2) UNSIGNED NOT NULL,
  `img` VARCHAR(255) NOT NULL,
  `desc` TEXT NULL,
  `status` TINYINT(8) UNSIGNED NOT NULL COMMENT '状态',
  PRIMARY KEY (`gid`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `fxuser`.`fx_reward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fxuser`.`fx_reward` (
  `rid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `money` DECIMAL(10,2) UNSIGNED NOT NULL COMMENT '红包金额',
  `note` VARCHAR(255) NULL COMMENT '备注',
  `type` TINYINT(8) UNSIGNED NOT NULL DEFAULT 0 COMMENT '红包类型',
  `uid` INT(10) UNSIGNED NOT NULL COMMENT '领取人id',
  `time` INT(10) UNSIGNED NOT NULL COMMENT '发放时间',
  `status` TINYINT(8) UNSIGNED NOT NULL COMMENT '领取状态',
  `price` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT 0 COMMENT '领取红包的最低级别',
  PRIMARY KEY (`rid`))
ENGINE = MyISAM
COMMENT = '回报表';


-- -----------------------------------------------------
-- Table `fxuser`.`fx_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fxuser`.`fx_admin` (
  `aid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL COMMENT '密码',
  `role` TINYINT(8) UNSIGNED NOT NULL COMMENT '角色',
  `city` TEXT NULL COMMENT '代理的代理城市代码',
  `time` INT(10) UNSIGNED NOT NULL COMMENT '添加时间',
  PRIMARY KEY (`aid`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `fxuser`.`fx_pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fxuser`.`fx_pay` (
  `pid` BIGINT NOT NULL,
  `oid` INT(10) NOT NULL COMMENT '订单id',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  `pay_time` DATETIME NULL COMMENT '支付时间',
  `status` TINYINT(8) NULL COMMENT '支付状态',
  `money` DECIMAL(10,2) UNSIGNED NOT NULL COMMENT '金额',
  `uid` INT(10) UNSIGNED NOT NULL COMMENT '支付用户',
  PRIMARY KEY (`pid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fxuser`.`fx_pack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fxuser`.`fx_pack` (
  `pid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade` VARCHAR(45) NULL COMMENT '商户订单号',
  `uid` INT(10) UNSIGNED NOT NULL COMMENT '用户id',
  `money` DECIMAL(10,2) NULL COMMENT '红包金额',
  `time` DATETIME NULL COMMENT '发放时间',
  PRIMARY KEY (`pid`))
ENGINE = MyISAM
COMMENT = '微信支付提现红包';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
